### PR TITLE
Party time

### PR DESCRIPTION
**Pull request by jprincipe**
- update colors to use hex values so we can take advantage of the standard color picker inputs
- added party flag that will make the cells render with a random color instead of the standard color

some additional party favors
- party music automatically starts when it's party time
- the Flame of Life logo now starts as a static png, and when partying changes to the animated gif

### CODE REVIEW

**Comment by BGRicker** [comment]
This is officially the best piece of software of all time with this feature, with my only concern being if we need to worry about the copyright of the song playing on here 😕

**Comment by BGRicker** [comment]
I don't want to be a cop, but from [the official rules](https://phoenixphrenzy.com/officialrules):

* `The submitted application does not contain (a) any image, picture, artwork, or other content owned by a third party unless you have obtained the necessary rights and licenses to use the same in your application; or (b) any image, name, likeness, biographical information, or personal information of an identifiable individual, unless prior written consent has been obtained from such individual(s) to display the same in your application or unless such use is otherwise lawful; and`
* `Your application does not violate, misappropriate or infringe any copyright, trademark, intellectual property rights, or other rights of any other person or entity.`

We can try to find whatever the version of an open source song is to replace it if we'd like, but it absolutely breaks my heart to be the one here to say that we probably shouldn't use this 😢

**Comment by BGRicker** [comment]
one other caveat with this that I noticed is that I think the color picker breaks a bit when you click and drag on there. I was hoping I could test out dragging on there to see the colors update in liveview, but I couldn't change the color after dragging. Probably not an issue or worth edits, but maybe it's just my machine anyways

**Comment by jprincipe** [comment]
@BGRicker super strange with the color picker... I noticed that too.  But yesterday the color picker was completely different

**Comment by jprincipe** [comment]
looks like it might be a chrome vs safari thing

**Comment by jprincipe** [comment]
I'm going to see if I can find a licensed version of the mp3 that we can use

**Pull request merged**
